create table "public"."diary" (
    "id" bigint generated by default as identity not null,
    "created_at" date not null default now(),
    "mood" smallint not null,
    "thoughts" text,
    "behaviour" text,
    "coping_strategies" text,
    "reassessment" text,
    "circumstance" text not null
);


alter table "public"."diary" enable row level security;

CREATE UNIQUE INDEX diary_pkey ON public.diary USING btree (id);

alter table "public"."diary" add constraint "diary_pkey" PRIMARY KEY using index "diary_pkey";


